export const warmUpCoolDownExercises = [
  {
    id: "1",
    program: "warm-up",
    name: "Jumping Jacks",
    instruction: [
      "Stand upright.",
      "Jump and extend your arms upward while spreading your legs.",
      "Return to the starting position.",
    ],
    reps: 20,
    duration: 30, // in seconds
    muscleGroup: ["Full Body", "Legs", "Shoulders"],
  },
  {
    id: "2",
    program: "warm-up",
    name: "High Knees",
    instruction: [
      "Run in place.",
      "Lift your knees as high as possible.",
      "Move your arms dynamically.",
    ],
    reps: 15,
    duration: 30,
    muscleGroup: ["Legs", "Core"],
  },
  {
    id: "3",
    program: "warm-up",
    name: "Arm Circles",
    instruction: [
      "Stand upright.",
      "Raise your arms to the sides.",
      "Make small circular movements.",
    ],
    reps: 10,
    duration: 20,
    muscleGroup: ["Shoulders"],
  },
  {
    id: "4",
    program: "warm-up",
    name: "Leg Swings",
    instruction: ["Stand on one leg.", "Swing the other leg back and forth."],
    reps: 10,
    duration: 30,
    muscleGroup: ["Quadriceps", "Hamstrings", "Hip Flexors"],
  },
  {
    id: "5",
    program: "warm-up",
    name: "Torso Twists",
    instruction: [
      "Stand upright with feet shoulder-width apart.",
      "Twist your torso from side to side.",
    ],
    reps: 15,
    duration: 30,
    muscleGroup: ["Core", "Obliques"],
  },
  {
    id: "6",
    program: "warm-up",
    name: "Arm Swings",
    instruction: [
      "Swing your arms alternately forward and backward.",
      "Loosen the shoulders.",
    ],
    reps: 10,
    duration: 20,
    muscleGroup: ["Shoulders", "Chest"],
  },
  {
    id: "7",
    program: "warm-up",
    name: "Hip Circles",
    instruction: [
      "Stand upright.",
      "Place your hands on your hips.",
      "Rotate your hips in large circles.",
    ],
    reps: 10,
    duration: 20,
    muscleGroup: ["Core", "Hip Flexors"],
  },
  {
    id: "8",
    program: "warm-up",
    name: "Ankle Hops",
    instruction: [
      "Lightly hop up and down on the balls of your feet.",
      "Mobilize your ankles.",
    ],
    reps: 15,
    duration: 30,
    muscleGroup: ["Calves", "Legs"],
  },
  {
    id: "9",
    program: "warm-up",
    name: "Plank Walkouts",
    instruction: [
      "Start in a standing position.",
      "Bend forward, place your hands on the floor.",
      "Walk out into a plank position.",
    ],
    reps: 10,
    duration: 40,
    muscleGroup: ["Core", "Shoulders"],
  },
  {
    id: "10",
    program: "warm-up",
    name: "Butt Kicks",
    instruction: ["Run in place.", "Try to kick your glutes with your heels."],
    reps: 20,
    duration: 30,
    muscleGroup: ["Hamstrings", "Glutes"],
  },
  {
    id: "11",
    program: "warm-up",
    name: "Inchworms",
    instruction: [
      "Stand upright.",
      "Bend down and walk your hands forward until you're in a plank position.",
    ],
    reps: 10,
    duration: 40,
    muscleGroup: ["Core", "Shoulders", "Hamstrings"],
  },
  {
    id: "12",
    program: "cool-down",
    name: "Child's Pose",
    instruction: [
      "Kneel down.",
      "Stretch your arms forward.",
      "Lower your forehead to the ground.",
    ],
    reps: 1,
    duration: 30,
    muscleGroup: ["Back", "Shoulders"],
  },
  {
    id: "13",
    program: "cool-down",
    name: "Hamstring Stretch",
    instruction: [
      "Sit on the floor.",
      "Extend one leg forward while the other remains bent.",
      "Lean forward over the extended leg.",
    ],
    reps: 1,
    duration: 30,
    muscleGroup: ["Hamstrings", "Lower Back"],
  },
  {
    id: "14",
    program: "cool-down",
    name: "Quad Stretch",
    instruction: [
      "Stand on one leg.",
      "Pull the other leg behind you to stretch the front of your thigh.",
    ],
    reps: 1,
    duration: 30,
    muscleGroup: ["Quadriceps"],
  },
  {
    id: "15",
    program: "cool-down",
    name: "Shoulder Stretch",
    instruction: [
      "Bring one arm across your body.",
      "Use the other arm to pull it closer to stretch your shoulders.",
    ],
    reps: 1,
    duration: 30,
    muscleGroup: ["Shoulders"],
  },
  {
    id: "16",
    program: "cool-down",
    name: "Seated Forward Fold",
    instruction: [
      "Sit with your legs extended forward.",
      "Lean over to stretch the back of your legs and lower back.",
    ],
    reps: 1,
    duration: 30,
    muscleGroup: ["Hamstrings", "Lower Back"],
  },
];
